//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKK.WindowsServiceHost.SvcComponentConfig {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DKK.WindowsServiceComponentConfig.v1", ConfigurationName="SvcComponentConfig.ISvcComponentConfig")]
    public interface ISvcComponentConfig {
        
        [System.ServiceModel.OperationContractAttribute(Action="DKK.WindowsServiceComponentConfig.v1/ISvcComponentConfig/GetEnvironments", ReplyAction="DKK.WindowsServiceComponentConfig.v1/ISvcComponentConfig/GetEnvironmentsResponse")]
        DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentsResponse GetEnvironments(DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKK.WindowsServiceComponentConfig.v1/ISvcComponentConfig/GetEnvironments", ReplyAction="DKK.WindowsServiceComponentConfig.v1/ISvcComponentConfig/GetEnvironmentsResponse")]
        System.Threading.Tasks.Task<DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentsResponse> GetEnvironmentsAsync(DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKK.WindowsServiceComponentConfig.v1/ISvcComponentConfig/GetEnvironmentConfig", ReplyAction="DKK.WindowsServiceComponentConfig.v1/ISvcComponentConfig/GetEnvironmentConfigResp" +
            "onse")]
        DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentConfigResponse GetEnvironmentConfig(DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKK.WindowsServiceComponentConfig.v1/ISvcComponentConfig/GetEnvironmentConfig", ReplyAction="DKK.WindowsServiceComponentConfig.v1/ISvcComponentConfig/GetEnvironmentConfigResp" +
            "onse")]
        System.Threading.Tasks.Task<DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentConfigResponse> GetEnvironmentConfigAsync(DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentConfigRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEnvironments", WrapperNamespace="DKK.WindowsServiceComponentConfig.v1", IsWrapped=true)]
    public partial class GetEnvironmentsRequest {
        
        public GetEnvironmentsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEnvironmentsResponse", WrapperNamespace="DKK.WindowsServiceComponentConfig.v1", IsWrapped=true)]
    public partial class GetEnvironmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DKK.WindowsServiceComponentConfig.v1", Order=0)]
        public System.Collections.Generic.List<string> GetEnvironmentsResult;
        
        public GetEnvironmentsResponse() {
        }
        
        public GetEnvironmentsResponse(System.Collections.Generic.List<string> GetEnvironmentsResult) {
            this.GetEnvironmentsResult = GetEnvironmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEnvironmentConfig", WrapperNamespace="DKK.WindowsServiceComponentConfig.v1", IsWrapped=true)]
    public partial class GetEnvironmentConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DKK.WindowsServiceComponentConfig.v1", Order=0)]
        public string environment;
        
        public GetEnvironmentConfigRequest() {
        }
        
        public GetEnvironmentConfigRequest(string environment) {
            this.environment = environment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEnvironmentConfigResponse", WrapperNamespace="DKK.WindowsServiceComponentConfig.v1", IsWrapped=true)]
    public partial class GetEnvironmentConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DKK.WindowsServiceComponentConfig.v1", Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string>> GetEnvironmentConfigResult;
        
        public GetEnvironmentConfigResponse() {
        }
        
        public GetEnvironmentConfigResponse(System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string>> GetEnvironmentConfigResult) {
            this.GetEnvironmentConfigResult = GetEnvironmentConfigResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcComponentConfigChannel : DKK.WindowsServiceHost.SvcComponentConfig.ISvcComponentConfig, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcComponentConfigClient : System.ServiceModel.ClientBase<DKK.WindowsServiceHost.SvcComponentConfig.ISvcComponentConfig>, DKK.WindowsServiceHost.SvcComponentConfig.ISvcComponentConfig {
        
        public SvcComponentConfigClient() {
        }
        
        public SvcComponentConfigClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcComponentConfigClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcComponentConfigClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcComponentConfigClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentsResponse GetEnvironments(DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentsRequest request) {
            return base.Channel.GetEnvironments(request);
        }
        
        public System.Threading.Tasks.Task<DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentsResponse> GetEnvironmentsAsync(DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentsRequest request) {
            return base.Channel.GetEnvironmentsAsync(request);
        }
        
        public DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentConfigResponse GetEnvironmentConfig(DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentConfigRequest request) {
            return base.Channel.GetEnvironmentConfig(request);
        }
        
        public System.Threading.Tasks.Task<DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentConfigResponse> GetEnvironmentConfigAsync(DKK.WindowsServiceHost.SvcComponentConfig.GetEnvironmentConfigRequest request) {
            return base.Channel.GetEnvironmentConfigAsync(request);
        }
    }
}
