//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKK.WindowsServiceHost.SvcHostConfig {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DKK.WindowsServiceHostConfig.v1", ConfigurationName="SvcHostConfig.ISvcHostConfig")]
    public interface ISvcHostConfig {
        
        [System.ServiceModel.OperationContractAttribute(Action="DKK.WindowsServiceHostConfig.v1/ISvcHostConfig/GetConfig", ReplyAction="DKK.WindowsServiceHostConfig.v1/ISvcHostConfig/GetConfigResponse")]
        DKK.WindowsServiceHost.SvcHostConfig.GetConfigResponse GetConfig(DKK.WindowsServiceHost.SvcHostConfig.GetConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKK.WindowsServiceHostConfig.v1/ISvcHostConfig/GetConfig", ReplyAction="DKK.WindowsServiceHostConfig.v1/ISvcHostConfig/GetConfigResponse")]
        System.Threading.Tasks.Task<DKK.WindowsServiceHost.SvcHostConfig.GetConfigResponse> GetConfigAsync(DKK.WindowsServiceHost.SvcHostConfig.GetConfigRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConfig", WrapperNamespace="DKK.WindowsServiceHostConfig.v1", IsWrapped=true)]
    public partial class GetConfigRequest {
        
        public GetConfigRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConfigResponse", WrapperNamespace="DKK.WindowsServiceHostConfig.v1", IsWrapped=true)]
    public partial class GetConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DKK.WindowsServiceHostConfig.v1", Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string>> GetConfigResult;
        
        public GetConfigResponse() {
        }
        
        public GetConfigResponse(System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string>> GetConfigResult) {
            this.GetConfigResult = GetConfigResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcHostConfigChannel : DKK.WindowsServiceHost.SvcHostConfig.ISvcHostConfig, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcHostConfigClient : System.ServiceModel.ClientBase<DKK.WindowsServiceHost.SvcHostConfig.ISvcHostConfig>, DKK.WindowsServiceHost.SvcHostConfig.ISvcHostConfig {
        
        public SvcHostConfigClient() {
        }
        
        public SvcHostConfigClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcHostConfigClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcHostConfigClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcHostConfigClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DKK.WindowsServiceHost.SvcHostConfig.GetConfigResponse GetConfig(DKK.WindowsServiceHost.SvcHostConfig.GetConfigRequest request) {
            return base.Channel.GetConfig(request);
        }
        
        public System.Threading.Tasks.Task<DKK.WindowsServiceHost.SvcHostConfig.GetConfigResponse> GetConfigAsync(DKK.WindowsServiceHost.SvcHostConfig.GetConfigRequest request) {
            return base.Channel.GetConfigAsync(request);
        }
    }
}
