// ------------------------------------------------------------------------------
// DO NOT MODIFY THIS CLASS - AutoGenerated Code
//    Any changes made to this code will be lost the next time this 
//    code is regenerated.
// 
//    Generated at: 9/27/2015 6:06:24 PM
//    DevForce version: 7.3.0.0
//    Template version: 2.1.4
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using IbCore = IdeaBlade.Core;
using IbEm = IdeaBlade.EntityModel;
using IbVal = IdeaBlade.Validation;

[module: IbCore.IdeaBladeLicense("kEX30kHh1PM0zb11Ypy2ByJ1WCZEP6S2oEi9zWHwrlvbui/yaFqqdMLdUFIEur+a")]

namespace DKK.DataModel
{

	#region DataModelEntities

	/// <summary>
	/// The domain-specific EntityManager for your domain model.
	/// </summary>
	public partial class DataModelEntities : IbEm.EntityManager {

    #region Constructors

    /// <summary>See <see cref="M:IbEm.EntityManager.#ctor(bool, string, IbEm.EntityServiceOption, string)"/>. </summary>
    public DataModelEntities(bool shouldConnect=true, string dataSourceExtension=null, IbEm.EntityServiceOption entityServiceOption=IbEm.EntityServiceOption.UseDefaultService, string compositionContextName=null) : base(shouldConnect, dataSourceExtension, entityServiceOption, compositionContextName) {}

    /// <summary>See <see cref="M:IbEm.EntityManager.#ctor(IbEm.EntityManagerContext)"/>. </summary>
    public DataModelEntities(IbEm.EntityManagerContext entityManagerContext) : base(entityManagerContext) {}

    /// <summary>See <see cref="M:IbEm.EntityManager.#ctor(IbEm.EntityManager, bool, string, IbEm.EntityServiceOption, string)"/>. </summary>
    public DataModelEntities(IbEm.EntityManager entityManager, bool shouldConnect, string dataSourceExtension=null, IbEm.EntityServiceOption entityServiceOption=IbEm.EntityServiceOption.UseDefaultService, string compositionContextName=null) : base(entityManager, shouldConnect, dataSourceExtension, entityServiceOption, compositionContextName) {}

    /// <summary>See <see cref="M:IbEm.EntityManager.#ctor(IbEm.EntityManager, IbEm.EntityManagerContext)"/>. </summary>
    public DataModelEntities(IbEm.EntityManager entityManager, IbEm.EntityManagerContext entityManagerContext=null) : base(entityManager, entityManagerContext) {}

    static DataModelEntities() {
      IbEm.EntityRelation.InitializeEntityRelations(IdeaBlade.Core.Reflection.ReflectionExtensions.GetAssembly(typeof(DataModelEntities)));
    }
    #endregion Constructors

    #region EntityQueries

    /// <summary>Gets the <see cref="T:IbEm.EntityQuery"/> associated with the given EntitySet name. </summary>
    public IbEm.EntityQuery<AutomatedLocation> AutomatedLocations {
      get { return new IbEm.EntityQuery<AutomatedLocation>("AutomatedLocations", this); }
    }
    #endregion EntityQueries
  }
  #endregion DataModelEntities

  #region AutomatedLocation class

  /// <summary>The auto-generated AutomatedLocation class. </summary>
  [DataContract(IsReference=true)]
  [IbEm.DataSourceKeyName(@"DataModelEntities")]
  [IbEm.DefaultEntitySetName(@"DataModelEntities.AutomatedLocations")]
  public partial class AutomatedLocation : EntityBase {

    /// <summary>Returns the property path for the given expression. </summary>
    /// <example>
    /// Usage:
    /// <code>
    ///    var r = Employee.PathFor(e => e.Manager.City); // returns "Manager.City"
    /// </code>
    /// </example>
    public static string PathFor(System.Linq.Expressions.Expression<System.Func<AutomatedLocation, object>> expr) {
      return IbCore.PropertyPath.For<AutomatedLocation>(expr);
    }

    #region Data Properties

    /// <summary>Gets or sets the Id. </summary>
    [Key]
    [DataMember]
    [Bindable(true, BindingDirection.OneWay)]
    [Editable(false)]
    [Display(Name="Id", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="AutomatedLocation_Id")]
    public System.Guid Id {
      get { return PropertyMetadata.Id.GetValue(this); }
      protected set { PropertyMetadata.Id.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Machine. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Machine", AutoGenerateField=true)]
    [IbVal.StringLengthVerifier(MaxValue=128, IsRequired=true, ErrorMessageResourceName="AutomatedLocation_Machine")]
    public string Machine {
      get { return PropertyMetadata.Machine.GetValue(this); }
      set { PropertyMetadata.Machine.SetValue(this, value); }
    }

    /// <summary>Gets or sets the LocalFolder. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="LocalFolder", AutoGenerateField=true)]
    [IbVal.StringLengthVerifier(MaxValue=256, IsRequired=true, ErrorMessageResourceName="AutomatedLocation_LocalFolder")]
    public string LocalFolder {
      get { return PropertyMetadata.LocalFolder.GetValue(this); }
      set { PropertyMetadata.LocalFolder.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Creator. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.OneWay)]
    [Editable(false)]
    [Display(Name="Creator", AutoGenerateField=true)]
    [IbVal.StringLengthVerifier(MaxValue=128, IsRequired=true, ErrorMessageResourceName="AutomatedLocation_Creator")]
    public string Creator {
      get { return PropertyMetadata.Creator.GetValue(this); }
      private set { PropertyMetadata.Creator.SetValue(this, value); }
    }

    /// <summary>Gets or sets the CreateDate. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.OneWay)]
    [Editable(false)]
    [Display(Name="CreateDate", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="AutomatedLocation_CreateDate")]
    public System.DateTimeOffset CreateDate {
      get { return PropertyMetadata.CreateDate.GetValue(this); }
      private set { PropertyMetadata.CreateDate.SetValue(this, value); }
    }

    /// <summary>Gets or sets the LastUpdater. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.OneWay)]
    [Editable(false)]
    [Display(Name="LastUpdater", AutoGenerateField=true)]
    [IbVal.StringLengthVerifier(MaxValue=128, IsRequired=false, ErrorMessageResourceName="AutomatedLocation_LastUpdater")]
    public string LastUpdater {
      get { return PropertyMetadata.LastUpdater.GetValue(this); }
      private set { PropertyMetadata.LastUpdater.SetValue(this, value); }
    }

    /// <summary>Gets or sets the LastUpdate. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.OneWay)]
    [Editable(false)]
    [Display(Name="LastUpdate", AutoGenerateField=true)]
    public System.Nullable<System.DateTimeOffset> LastUpdate {
      get { return PropertyMetadata.LastUpdate.GetValue(this); }
      private set { PropertyMetadata.LastUpdate.SetValue(this, value); }
    }

    /// <summary>Gets or sets the RowVersion. </summary>
    [DataMember]
    [IbEm.ConcurrencyStrategy(IbEm.ConcurrencyStrategy.AutoIncrement)]
    [Bindable(true, BindingDirection.OneWay)]
    [Editable(false)]
    [Display(Name="RowVersion", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="AutomatedLocation_RowVersion")]
    public int RowVersion {
      get { return PropertyMetadata.RowVersion.GetValue(this); }
      private set { PropertyMetadata.RowVersion.SetValue(this, value); }
    }
    #endregion Data Properties

    #region Navigation properties
    #endregion Navigation properties

    #region EntityProperty definitions
    public partial class PropertyMetadata {

      /// Explicit static constructor ensures static fields are initialized.
      static PropertyMetadata() {}

      /// <summary>The Id <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<AutomatedLocation, System.Guid> Id = new IbEm.DataEntityProperty<AutomatedLocation, System.Guid>("Id", false, true, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Machine <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<AutomatedLocation, string> Machine = new IbEm.DataEntityProperty<AutomatedLocation, string>("Machine", false, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The LocalFolder <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<AutomatedLocation, string> LocalFolder = new IbEm.DataEntityProperty<AutomatedLocation, string>("LocalFolder", false, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Creator <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<AutomatedLocation, string> Creator = new IbEm.DataEntityProperty<AutomatedLocation, string>("Creator", false, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The CreateDate <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<AutomatedLocation, System.DateTimeOffset> CreateDate = new IbEm.DataEntityProperty<AutomatedLocation, System.DateTimeOffset>("CreateDate", false, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The LastUpdater <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<AutomatedLocation, string> LastUpdater = new IbEm.DataEntityProperty<AutomatedLocation, string>("LastUpdater", true, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The LastUpdate <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<AutomatedLocation, System.Nullable<System.DateTimeOffset>> LastUpdate = new IbEm.DataEntityProperty<AutomatedLocation, System.Nullable<System.DateTimeOffset>>("LastUpdate", true, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The RowVersion <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<AutomatedLocation, int> RowVersion = new IbEm.DataEntityProperty<AutomatedLocation, int>("RowVersion", false, false, IbEm.ConcurrencyStrategy.AutoIncrement, false, null);
    }
    #endregion EntityProperty definitions

    #region EntityPropertyNames
    public new partial class EntityPropertyNames : EntityBase.EntityPropertyNames {
      public const String Id = "Id";
      public const String Machine = "Machine";
      public const String LocalFolder = "LocalFolder";
      public const String Creator = "Creator";
      public const String CreateDate = "CreateDate";
      public const String LastUpdater = "LastUpdater";
      public const String LastUpdate = "LastUpdate";
      public const String RowVersion = "RowVersion";
    }
    #endregion EntityPropertyNames
  }
  #endregion AutomatedLocation class

  #region Injected base classes
  [DataContract(IsReference=true)]
  [IbEm.DiscoverableType(IbEm.DiscoverableTypeMode.KnownType)]
  public abstract partial class EntityBase : IbEm.Entity {
  }
  #endregion Injected base classes

  #region EntityRelations

  /// <summary>
  /// A generated class that returns the relations between entities in this model.
  /// </summary>
  [IbCore.IdeaBladeGuid("f99b2625-2736-49ce-bf95-4423510189f6", "2.1.4")]
  public partial class EntityRelations : IbEm.IEntityRelations {

    /// Explicit static constructor ensures static fields are initialized.
    static EntityRelations() {}
  }
  #endregion EntityRelations
}
